# Generated by Django 5.2.6 on 2025-09-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joke_sets', '0001_initial'),
        ('jokes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jokeset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jokesetjoke',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.joke'),
        ),
        migrations.AddField(
            model_name='jokesetjoke',
            name='joke_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joke_items', to='joke_sets.jokeset'),
        ),
        migrations.AddField(
            model_name='jokesetjoke',
            name='toppers',
            field=models.ManyToManyField(blank=True, to='jokes.topper'),
        ),
    ]
