# Generated by Django 5.2.6 on 2025-09-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jokes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joke',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokes', to='jokes.category'),
        ),
        migrations.AddField(
            model_name='topper',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppers', to='jokes.joke'),
        ),
    ]
