# Generated by Django 5.2.6 on 2025-10-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JokeSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.joke')),
                ('joke_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jokes.jokeset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('joke_set', 'joke')},
            },
        ),
        migrations.CreateModel(
            name='JokeSetTopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('joke_set_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_toppers', to='jokes.jokesetitem')),
                ('topper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.topper')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('joke_set_item', 'topper')},
            },
        ),
    ]
